services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings